import {$,sprite,reducedMotion,bestScore,clearScores,connectSound} from './common.js';
const canvas=$('flick-canvas'),c=canvas.getContext('2d'),tone=connectSound();
const gravity=700,speed=780,origin={x:105,y:340};
let tom=null,dog=null,flight=null,shots=5,score=0,round=0,elapsed=0,last=0,paused=false,done=false;
let target={x:590,y:215},sparkles=[],loadFailure=false;
const hits=['A good look. A GREAT throw.','Designer delivery. No signature required.','Bad fashion has left the building.','Absolutely hat-standing.','Style: aggressively delivered.'];
Promise.all([sprite('tom-jump.png',8),sprite('memphis-idle.png',8,180)]).then(([t,d])=>{tom=t;dog=d;}).catch(()=>{loadFailure=true;$('message').textContent='Character art could not load. The target and throwing controls still work; reload to restore the crew.';});
function targetPoint(){return {x:target.x+(reducedMotion.matches?0:Math.sin(elapsed*1.5)*23),y:target.y};}
function sync(){ $('score').textContent=score;$('shots').textContent=shots;$('best').textContent=bestScore('flick');$('flick').disabled=!!flight||paused||done;$('aim').disabled=!!flight||paused||done;$('pause').disabled=done;$('pause').textContent=paused?'Resume':'Pause';$('pause').setAttribute('aria-pressed',String(paused));$('motion-note').textContent=reducedMotion.matches?'STILL TARGET · REDUCED MOTION':''; }
function newRound(){flight=null;shots=5;score=0;round=0;elapsed=0;paused=false;done=false;sparkles=[];target={x:590,y:215};$('aim').value=35;$('angle').value='35°';$('result').hidden=true;$('message').textContent='Five hats. Aim the dotted arc through the yellow ring. You have all the time you need.';sync();}
function shoot(){if(flight||paused||done)return;const radians=Number($('aim').value)*Math.PI/180;shots--;flight={x:origin.x,y:origin.y,vx:Math.cos(radians)*speed,vy:-Math.sin(radians)*speed,age:0};$('message').textContent='A very confident hat is in transit.';sync();}
function settle(hit){flight=null;round++;if(hit){score+=100;tone(true);const p=targetPoint();sparkles=reducedMotion.matches?[]:Array.from({length:12},(_,i)=>({x:p.x,y:p.y,vx:Math.cos(i*Math.PI/6)*90,vy:Math.sin(i*Math.PI/6)*90,life:.6}));$('message').textContent=hits[(round-1)%hits.length];}else{tone(false);$('message').textContent='Missed the ring. Same confidence, slightly different angle next time.';}
 if(shots===0){done=true;bestScore('flick',score);$('result').textContent=score>=400?'STYLE ICON. '+score+' / 500. Memphis is impressed.':score>=200?'LOOKING GOOD. '+score+' / 500. One more round?':'QUESTIONABLE DECISIONS. '+score+' / 500. The hat believes in you.';$('result').hidden=false;$('restart').focus();}
 else{target={x:530+Math.random()*105,y:195+Math.random()*70};}sync();}
function pause(){if(done)return;paused=!paused;$('message').textContent=paused?'Paused. Your hats are going nowhere.':'Back in business. Aim, then flick.';sync();}
function hat(x,y,rotation=0){c.save();c.translate(x,y);c.rotate(rotation);c.fillStyle='#121c24';c.strokeStyle='#f8dfb2';c.lineWidth=2;c.beginPath();c.roundRect(-12,-12,24,14,4);c.fill();c.stroke();c.fillStyle='#ff654e';c.fillRect(-12,-3,24,4);c.fillStyle='#121c24';c.fillRect(-22,2,44,6);c.strokeRect(-22,2,44,6);c.restore();}
function draw(){c.clearRect(0,0,800,450);c.fillStyle='#122c40';c.fillRect(0,0,800,450);c.fillStyle='#bfd0bf';c.beginPath();c.arc(705,66,29,0,Math.PI*2);c.fill();
 for(let i=0;i<12;i++){const h=80+(i*43%120);c.fillStyle=i%2?'#1c3d4c':'#214757';c.fillRect(i*75,360-h,58,h);c.fillStyle='#557272';for(let row=0;row<4;row++)c.fillRect(i*75+12,375-h+row*28,13,8);}
 c.fillStyle='#091c29';c.fillRect(0,375,800,75);c.fillStyle='#6d8580';c.fillRect(0,371,800,7);c.fillStyle='#243e46';for(let x=0;x<800;x+=80)c.fillRect(x+3,393,74,2);
 c.fillStyle='#f4eddd';c.font='800 12px system-ui';c.fillText('ROOFTOP PRACTICE. QUESTIONABLE DRESS CODE.',22,28);
 const t=targetPoint();c.strokeStyle='#5a7877';c.lineWidth=8;c.beginPath();c.moveTo(t.x,375);c.lineTo(t.x,t.y+27);c.stroke();c.strokeStyle='#e3f379';c.lineWidth=7;c.beginPath();c.ellipse(t.x,t.y,33,28,0,0,Math.PI*2);c.stroke();c.fillStyle='#e3f379';c.font='bold 11px system-ui';c.textAlign='center';c.fillText('LAND THE LOOK',t.x,t.y-47);c.textAlign='left';
 if(tom)tom.draw(c,flight?3:0,32,245,148);else{c.fillStyle='#ff654e';c.fillRect(70,320,25,51);c.fillStyle='#f4eddd';c.font='11px system-ui';c.fillText(loadFailure?'ART OFFLINE':'LOADING CREW',22,421);}
 if(dog)dog.draw(c,0,186,303,104);
 if(!flight&&!done){const a=Number($('aim').value)*Math.PI/180;for(let age=.08;age<1.12;age+=.08){const x=origin.x+Math.cos(a)*speed*age,y=origin.y-Math.sin(a)*speed*age+.5*gravity*age*age;if(y>371)break;c.fillStyle=age<.8?'#f4eddd9a':'#f4eddd40';c.beginPath();c.arc(x,y,2.3,0,Math.PI*2);c.fill();}hat(origin.x,origin.y);}
 if(flight)hat(flight.x,flight.y,reducedMotion.matches?0:flight.age*8);
 for(const s of sparkles){c.globalAlpha=Math.max(0,s.life/.6);c.fillStyle='#e3f379';c.fillRect(s.x,s.y,5,5);}c.globalAlpha=1;
 if(paused||done){c.fillStyle='#07171dcc';c.fillRect(0,0,800,450);c.fillStyle='#f4eddd';c.textAlign='center';c.font='44px Impact, sans-serif';c.fillText(paused?'STYLE BREAK.':score>=400?'ABSOLUTELY HAT-STANDING.':'THAT’S A WRAP.',400,208);c.font='16px system-ui';c.fillText(paused?'Press Resume when you’re ready.':score+' style points · New Round to try again',400,248);c.textAlign='left';}}
function frame(now){const dt=Math.min(Math.max(0,(now-last)/1000),.04);last=now;if(!paused&&!done&&!document.hidden){elapsed+=dt;if(flight){const start={x:flight.x,y:flight.y};flight.age+=dt;flight.vy+=gravity*dt;flight.x+=flight.vx*dt;flight.y+=flight.vy*dt;const t=targetPoint();const dx=flight.x-start.x,dy=flight.y-start.y,length=dx*dx+dy*dy;const u=length?Math.min(1,Math.max(0,((t.x-start.x)*dx+(t.y-start.y)*dy)/length)):0;const dist=Math.hypot(start.x+dx*u-t.x,start.y+dy*u-t.y);if(dist<25)settle(true);else if(flight&&(flight.y>382||flight.x>835||flight.age>4))settle(false);}
 for(const s of sparkles){s.x+=s.vx*dt;s.y+=s.vy*dt;s.life-=dt;}sparkles=sparkles.filter(s=>s.life>0);}
 draw();requestAnimationFrame(frame);}
$('aim').addEventListener('input',()=>{$('angle').value=$('aim').value+'°';});$('flick').addEventListener('click',shoot);$('pause').addEventListener('click',pause);$('restart').addEventListener('click',newRound);$('clear').addEventListener('click',()=>{$('message').textContent=clearScores()?'Local best scores cleared. Current round continues.':'Browser storage is unavailable; scores only last this session.';sync();});
document.addEventListener('visibilitychange',()=>{if(document.hidden&&!done&&!paused){paused=true;sync();$('message').textContent='Paused while you were away. Press Resume to continue.';}});window.addEventListener('blur',()=>{if(flight&&!paused&&!done){paused=true;sync();$('message').textContent='Paused when focus moved away. Press Resume to continue.';}});reducedMotion.addEventListener('change',sync);newRound();requestAnimationFrame(frame);
